export const CHANGE_CAR_PARAMS_LIST = 'CHANGE_CAR_PARAMS_LIST'
export const CHANGE_SHOW_EDITION = 'CHANGE_SHOW_EDITION'
export const CHANGE_SHOW_MODAL_CAR_DETAIL = 'CHANGE_SHOW_MODAL_CAR_DETAIL'
export const CHANGE_IS_FIXED = 'CHANGE_IS_FIXED'
export const CHANGE_COLOR = 'CHANGE_COLOR'
export const CHANGE_WHEEL = 'CHANGE_WHEEL'
export const CHANGE_DECORATION = 'CHANGE_DECORATION'

